name: Test

on:
  push:
    branches:
      - dev

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"

      - name: install dependencies
        run: go mod download

      - name: go build
        run: go build ./cmd/main.go

      - name: go test
        run: go test ./internal/...
